### ISSUE TITLE
不能用的话如何卸载？

### ISSUE THREAD

**Issue by Xander-Y** [BrightX/rtl8192fu#1]
我也下载了这个，ubuntu 20.04 5.4内核，还没装，不知道能不能用。安装了的话应该如何卸载？

**Comment by BrightX** [comment]
> 我也下载了这个，ubuntu 20.04 5.4内核，还没装，不知道能不能用。安装了的话应该如何卸载？

卸载的话，很简单。使用以下方式卸载：
```bash
# 从内核中移除已加载的模块
sudo rmmod 8192fu
# 进入源码目录
cd rtl8192fu/
# 通过make命令卸载
sudo make uninstall
```
