### ISSUE TITLE
rtl8192fu编译并安装成功后 无法装载到内核  求解

### ISSUE THREAD

**Issue by KKDAChou** [BrightX/rtl8192fu#11]
Device Information | 设备信息

SOC: [S905l3a]
Model [m401a]
Armbian Version | 系统版本

Kernel Version: [5.15.92]
Release: [bullseye]

armbian:/rtl8192fu:# sudo modprobe 8192fu                          
modprobe: ERROR: could not insert '8192fu': Exec format error

![R}WMZ~H3EOAVZJCV83W3`0V](https://user-images.githubusercontent.com/126685754/229996460-0ccdb708-6be8-4edc-8f5f-884350549a29.png)

**Comment by BrightX** [comment]
这个应该是指令集的问题，你可以修改一下[`Makefile`的第127行](https://github.com/BrightX/rtl8192fu/blob/master/Makefile#L127) 将 `CONFIG_PLATFORM_I386_PC` 设置为`n`，然后将对应的`CONFIG_PLATFORM_****`选项设置为`y`。然后重新编译安装。

**Comment by KKDAChou** [comment]
大佬 我是armbian  貌似没有对应的  还是说我找错了 芯片是s905-l3a     arm64位架构
- CONFIG_PLATFORM_ARM_PXA2XX
- CONFIG_PLATFORM_ARM_S3C6K4
- CONFIG_PLATFORM_ARM_MX51_241H
- CONFIG_PLATFORM_ARM_TCC8900
- CONFIG_PLATFORM_ARM_TCC8920
- CONFIG_PLATFORM_ARM_TCC8920_JB42
- CONFIG_PLATFORM_ARM_TCC8930_JB42
- CONFIG_PLATFORM_ARM_RK2818
- CONFIG_PLATFORM_ARM_RK3066
- CONFIG_PLATFORM_ARM_RK3188
- CONFIG_PLATFORM_ARM_URBETTER
- CONFIG_PLATFORM_ARM_TI_PANDA
- CONFIG_PLATFORM_ARM_SUNxI
- CONFIG_PLATFORM_ARM_SUN6I
- CONFIG_PLATFORM_ARM_SUN7I
- CONFIG_PLATFORM_ARM_SUN8I_W3P1
- CONFIG_PLATFORM_ARM_SUN8I_W5P1
- CONFIG_PLATFORM_ARM_SPREADTRUM_6820
- CONFIG_PLATFORM_ARM_SPREADTRUM_8810
- CONFIG_PLATFORM_ARM_WMT

**Comment by KKDAChou** [comment]
编译的时候有指定arm64位
![`~XOMLOM((KRB2P9Z2~VBTJ](https://user-images.githubusercontent.com/126685754/230015382-9151dba2-7014-4668-9a1d-8f5d7f465076.png)

**Comment by BrightX** [comment]
我更新了一下 Makefile，你更新一下代码，然后将 `CONFIG_PLATFORM_I386_PC` 设为 `n`， 将 `CONFIG_PLATFORM_ARM_AARCH64` 设为 `y`。再试一下。

**Comment by KKDAChou** [comment]
重新拉了代码 编译安装挂载还是这个报错 呜呜呜
![77LJJD 4PS@DS _K 2G}MHY](https://user-images.githubusercontent.com/126685754/230024366-9745a4dc-acd7-4831-ad87-d6ca2d75b344.png)

**Comment by KKDAChou** [comment]
貌似找到原因了 大佬这几个参数编译的时候可选择嘛 
![8~{MB)LYU99P31V}@F8B)DJ](https://user-images.githubusercontent.com/126685754/230057283-fcfa5100-2ddd-476e-bf61-9543634a4eb3.png)
![L}BU}AZ6ECOK}DQ P{4ASHP](https://user-images.githubusercontent.com/126685754/230057326-92518f3e-83d6-4ff1-a516-4bbcad522ef3.png)
