### ISSUE TITLE
ArchLinuxARM安装报错

### ISSUE THREAD

**Issue by GuyCui** [BrightX/rtl8192fu#15]
内核版本：6.8.9-1-aarch64-ARCH
错误：make ARCH=arm64 CROSS_COMPILE= -C /lib/modules/6.8.9-1-aarch64-ARCH/build M=/home/alarm/rtl8192fu  modules
make[1]: 进入目录“/usr/lib/modules/6.8.9-1-aarch64-ARCH/build”
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-unknown-linux-gnu-gcc (GCC) 12.1.0
  You are using:           gcc (GCC) 14.1.1 20240507
  CC [M]  /home/alarm/rtl8192fu/os_dep/linux/usb_intf.o
/home/alarm/rtl8192fu/os_dep/linux/usb_intf.c:326:17: 错误：‘struct usb_driver’没有名为‘drvwrap’的成员
  326 |         .usbdrv.drvwrap.driver.shutdown = rtw_dev_shutdown,
      |                 ^~~~~~~
/home/alarm/rtl8192fu/os_dep/linux/usb_intf.c:326:43: 错误：initialization of ‘const char *’ from incompatible pointer type ‘void (*)(struct device *)’ [-Wincompatible-pointer-types]
  326 |         .usbdrv.drvwrap.driver.shutdown = rtw_dev_shutdown,
      |                                           ^~~~~~~~~~~~~~~~
/home/alarm/rtl8192fu/os_dep/linux/usb_intf.c:326:43: 附注：(在‘usb_drv.usbdrv.name’的初始化附近)
/home/alarm/rtl8192fu/os_dep/linux/usb_intf.c:991:5: 警告：‘rtw_resume_process’先前没有原型 [-Wmissing-prototypes]
  991 | int rtw_resume_process(_adapter *padapter)
      |     ^~~~~~~~~~~~~~~~~~
/home/alarm/rtl8192fu/os_dep/linux/usb_intf.c:1245:11: 警告：‘rtw_usb_primary_adapter_init’先前没有原型 [-Wmissing-prototypes]
 1245 | _adapter *rtw_usb_primary_adapter_init(struct dvobj_priv *dvobj,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:243：/home/alarm/rtl8192fu/os_dep/linux/usb_intf.o] 错误 1
make[2]: *** [/usr/lib/modules/6.8.9-1-aarch64-ARCH/build/Makefile:1921：/home/alarm/rtl8192fu] 错误 2
make[1]: *** [Makefile:240：__sub-make] 错误 2
make[1]: 离开目录“/usr/lib/modules/6.8.9-1-aarch64-ARCH/build”
make: *** [Makefile:2354：modules] 错误 2

**Comment by BrightX** [comment]
该驱动支持的linux内核版本最高是6.4，从linux6.5开始已经内置了该驱动，所以不必再单独安装。
参考：https://github.com/torvalds/linux/commit/c98411dc8cf6c15b8dbbfb37475bcc08b8958880

**Comment by GuyCui** [comment]
> 该驱动支持的linux内核版本最高是6.4，从linux6.5开始已经内置了该驱动，所以不需要再单独安装。 参考：[torvalds/linux@ c98411d](https://github.com/torvalds/linux/commit/c98411dc8cf6c15b8dbbfb37475bcc08b8958880)

感谢提供帮助 希望下一位小伙伴遇到这个问题再执行下 `sudo usb_modeswitch -v 0bda -p a192 -KW`这个命令进行切换
