### ISSUE TITLE
Linuxhead没法下载

### ISSUE THREAD

**Issue by Yubadboy201** [BrightX/rtl8192fu#2]
我用了你的命令出现没找到，我是kali2020.4

**Comment by BrightX** [comment]
暂不支持 kali2020.4 你可以试试 https://gitee.com/BrightXu/rtl8192fu2

**Comment by Yubadboy201** [comment]
/bin/sh: 1: bc: not found
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.9.0-kali1-amd64/build M=/home/yubadboy/netqd/rtl8192fu2  modules
make[1]: *** /lib/modules/5.9.0-kali1-amd64/build: 没有那个文件或目录。 停止。
make: *** [Makefile:2327：modules] 错误 2

**Comment by BrightX** [comment]
你试试以下命令，然后再继续
```bash
sudo apt install bc linux-headers-$(uname -r) -y
```
