### ISSUE TITLE
Monitor mode not working

### ISSUE THREAD

**Issue by AlienWolfX** [BrightX/rtl8192fu#3]
English: Hello Good day, I would like to ask if the Device or the Driver supports monitor mode as i failed to get it to work
Chinese: 您好,好,我想问一下设备或驱动程序支持监视器模式是否无法正常工作。
Ps: Sorry if the translation is messed up I used google translate

**Comment by BrightX** [comment]
OK, you can try to change `CONFIG_WIFI_MONITOR = n` to `CONFIG_WIFI_MONITOR = y` at about line 78 of the file `Makefile`. And use the command `make -j$(nproc)` to recompile.

**Comment by AlienWolfX** [comment]
Do I need to Uninstall the old driver first.?

**Comment by BrightX** [comment]
Yes, you can execute the command `rmmod 8192fu` and `make uninstall` to uninstall it.

**Comment by AlienWolfX** [comment]
Does the driver or chip supports VIF.? I can't get it to work with airgeddon and fluxion

**Comment by BrightX** [comment]
Sorry, I don't know. 😅😅😅

**Comment by AlienWolfX** [comment]
Oh It's okay At least the monitor mode is working lol, Thank you very much
