### ISSUE TITLE
Monitor mode?

### ISSUE THREAD

**Issue by peddy22** [BrightX/rtl8192fu#4]
Can the driver enable monitor mode? Thanks

**Comment by BrightX** [comment]
> Can the driver enable monitor mode? Thanks

Yes. You can refer to https://github.com/BrightX/rtl8192fu/issues/3#issuecomment-962419503

**Comment by peddy22** [comment]
Thanks, it was already enabled, looks like an issue on Arch Linux. Works fine on Debian.
