### ISSUE TITLE
/root/rtl8192fu-1.0/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory

### ISSUE THREAD

**Issue by alanOO7** [BrightX/rtl8192fu#6]
5.16.0-kali7-amd64

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.16.0-kali7-amd64/build M=/root/rtl8192fu-1.0  modules
make[1]: Entering directory '/usr/src/linux-headers-5.16.0-kali7-amd64'
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc-11 (Debian 11.2.0-19) 11.2.0
  You are using:           gcc-11 (Debian 11.3.0-3) 11.3.0
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
  CC [M]  /root/rtl8192fu-1.0/core/rtw_br_ext.o
  CC [M]  /root/rtl8192fu-1.0/core/rtw_btcoex_wifionly.o
  CC [M]  /root/rtl8192fu-1.0/core/rtw_btcoex.o
  CC [M]  /root/rtl8192fu-1.0/core/rtw_beamforming.o
/root/rtl8192fu-1.0/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>
      |                  ^~~~~~~~~~~
compilation terminated.
make[2]: *** [/usr/src/linux-headers-5.16.0-kali7-common/scripts/Makefile.build:292: /root/rtl8192fu-1.0/core/rtw_br_ext.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-5.16.0-kali7-common/Makefile:1870: /root/rtl8192fu-1.0] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.16.0-kali7-amd64'
make: *** [Makefile:2327: modules] Error 2
                                                                             
┌──(root㉿kali)-[~/rtl8192fu-1.0]
└─# make -j$(nproc)

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.16.0-kali7-amd64/build M=/root/rtl8192fu-1.0  modules
make[1]: Entering directory '/usr/src/linux-headers-5.16.0-kali7-amd64'
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc-11 (Debian 11.2.0-19) 11.2.0
  You are using:           gcc-11 (Debian 11.3.0-3) 11.3.0
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
  CC [M]  /root/rtl8192fu-1.0/core/rtw_br_ext.o
  CC [M]  /root/rtl8192fu-1.0/core/rtw_odm.o
  CC [M]  /root/rtl8192fu-1.0/core/rtw_rm.o
  CC [M]  /root/rtl8192fu-1.0/core/rtw_rm_fsm.o
/root/rtl8192fu-1.0/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>
      |                  ^~~~~~~~~~~
compilation terminated.
make[2]: *** [/usr/src/linux-headers-5.16.0-kali7-common/scripts/Makefile.build:292: /root/rtl8192fu-1.0/core/rtw_br_ext.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-5.16.0-kali7-common/Makefile:1870: /root/rtl8192fu-1.0] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.16.0-kali7-amd64'
make: *** [Makefile:2327: modules] Error 2

这版本不行吗

**Comment by BrightX** [comment]
兄嘚，麻烦你拉取一下最新的驱动代码，这个问题我早就修复了呀。😅😅 
https://github.com/BrightX/rtl8192fu/commit/9a7a773875ecd4dcb1a64be6e421eca249256955
