### ISSUE TITLE
Not working with TP Link 822n

### ISSUE THREAD

**Issue by nerdblaze** [BrightX/rtl8192fu#7]
After installing the driver it's not getting detected in Garuda Linux ( Arch, LTS 5.15.44)
This usb adapter is using same chipset 8192eu. Can U please add support for that?
VID: 2357
PID: 0108

**Comment by BrightX** [comment]
Oh, sorry. They are not the same product and I am not sure it will work properly. You can try this driver: https://github.com/Mange/rtl8192eu-linux-driver .

**Comment by nerdblaze** [comment]
I found 2 references of the same in makefile at line 39  and as well as in the ./os_dep/linux/usb_intf.c file at line 197.
That driver U pointed out doesn't have packet injection.
Can U please just look into that?

**Comment by BrightX** [comment]
😅😅Sorry, that's just the config file, the code doesn't implement it.
