### ISSUE TITLE
About the problem of using the driver when SecureBoot is turned on

### ISSUE THREAD

**Issue by qyvip** [BrightX/rtl8192fu#8]
At present, the driver has been successfully installed in ubuntu, but the driver can only be loaded when SecureBoot is turned off. Does this mean that SecureBoot must be turned off, or is there any way to successfully load the driver when SecureBoot is turned on?

**Comment by BrightX** [comment]
This problem generally exists, although I haven't tried it, but you can try the following solution. After executing the `make -j8` command, first you can sign the compiled kernel module file `8192fu.ko`, and then execute the `make install` command. Specific reference: https://ubuntu.com/blog/how-to-sign-things-for-secure-boot .

**Comment by BrightX** [comment]
I wrote a Wiki Page [SecureBoot 安全引导下驱动模块启动](https://github.com/BrightX/rtl8192fu/wiki/SecureBoot-%E5%AE%89%E5%85%A8%E5%BC%95%E5%AF%BC%E4%B8%8B%E9%A9%B1%E5%8A%A8%E6%A8%A1%E5%9D%97%E5%90%AF%E5%8A%A8) that I hope will help you.
