### ISSUE TITLE
kernel version 6

### ISSUE THREAD

**Issue by faroukchebaiki** [BrightX/rtl8192fu#9]
can i found drivers for Linux kernel version 6 or something that work with it

**Comment by BrightX** [comment]
What? Can you explain it in detail? Or an example?

**Comment by faroukchebaiki** [comment]
I wanted to install this driver on PopOS (last kernel version), but I couldn't. Is there a solution?

**Comment by BrightX** [comment]
> I wanted to install this driver on PopOS (last kernel version), but I couldn't. Is there a solution?

Could you describe your problem in more detail? Such as `uname -r`, and error messages at compile time.

**Comment by faroukchebaiki** [comment]
farouk@pop-os:~$ sudo apt install -y linux-headers-$(uname -r)
[sudo] password for farouk: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
linux-headers-6.0.6-76060006-generic is already the newest version (6.0.6-76060006.202210290932~1667401208~22.04~d2df702).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up broadcom-sta-dkms (6.30.223.271-17) ...
Removing old broadcom-sta-6.30.223.271 DKMS files...
Deleting module broadcom-sta-6.30.223.271 completely from the DKMS tree.
Loading new broadcom-sta-6.30.223.271 DKMS files...
Building for 6.0.6-76060006-generic
Building initial module for 6.0.6-76060006-generic
ERROR (dkms apport): kernel package linux-headers-6.0.6-76060006-generic is not supported
Error! Bad return status for module build on kernel: 6.0.6-76060006-generic (x86_64)
Consult /var/lib/dkms/broadcom-sta/6.30.223.271/build/make.log for more information.
dpkg: error processing package broadcom-sta-dkms (--configure):
 installed broadcom-sta-dkms package post-installation script subprocess returne
d error exit status 10
Setting up rtl8192fu-dkms (5.8.6.2~jammy10) ...
Removing old rtl8192fu-5.8.6.2~ppa DKMS files...
Deleting module rtl8192fu-5.8.6.2~ppa completely from the DKMS tree.
Loading new rtl8192fu-5.8.6.2~ppa DKMS files...
Building for 6.0.6-76060006-generic
Building initial module for 6.0.6-76060006-generic
ERROR (dkms apport): kernel package linux-headers-6.0.6-76060006-generic is not 
supported
Error! Bad return status for module build on kernel: 6.0.6-76060006-generic (x86
_64)
Consult /var/lib/dkms/rtl8192fu/5.8.6.2~ppa/build/make.log for more information.
dpkg: error processing package rtl8192fu-dkms (--configure):
 installed rtl8192fu-dkms package post-installation script subprocess returned e
rror exit status 10
Errors were encountered while processing:
 broadcom-sta-dkms
 rtl8192fu-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by BrightX** [comment]
> 
> farouk@pop-os:~$ sudo apt install -y linux-headers-$(uname -r)
> [sudo] password for farouk: 
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> linux-headers-6.0.6-76060006-generic is already the newest version (6.0.6-76060006.202210290932~1667401208~22.04~d2df702).
> 0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
> 2 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Setting up broadcom-sta-dkms (6.30.223.271-17) ...
> Removing old broadcom-sta-6.30.223.271 DKMS files...
> Deleting module broadcom-sta-6.30.223.271 completely from the DKMS tree.
> Loading new broadcom-sta-6.30.223.271 DKMS files...
> Building for 6.0.6-76060006-generic
> Building initial module for 6.0.6-76060006-generic
> ERROR (dkms apport): kernel package linux-headers-6.0.6-76060006-generic is not supported
> Error! Bad return status for module build on kernel: 6.0.6-76060006-generic (x86_64)
> Consult /var/lib/dkms/broadcom-sta/6.30.223.271/build/make.log for more information.
> dpkg: error processing package broadcom-sta-dkms (--configure):
>  installed broadcom-sta-dkms package post-installation script subprocess returne
> d error exit status 10
> Setting up rtl8192fu-dkms (5.8.6.2~jammy10) ...
> Removing old rtl8192fu-5.8.6.2~ppa DKMS files...
> Deleting module rtl8192fu-5.8.6.2~ppa completely from the DKMS tree.
> Loading new rtl8192fu-5.8.6.2~ppa DKMS files...
> Building for 6.0.6-76060006-generic
> Building initial module for 6.0.6-76060006-generic
> ERROR (dkms apport): kernel package linux-headers-6.0.6-76060006-generic is not 
> supported
> Error! Bad return status for module build on kernel: 6.0.6-76060006-generic (x86
> _64)
> Consult /var/lib/dkms/rtl8192fu/5.8.6.2~ppa/build/make.log for more information.
> dpkg: error processing package rtl8192fu-dkms (--configure):
>  installed rtl8192fu-dkms package post-installation script subprocess returned e
> rror exit status 10
> Errors were encountered while processing:
>  broadcom-sta-dkms
>  rtl8192fu-dkms
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> 

This driver `rtl8192fu-dkms(ppa)` is not maintained by me, please remove it first and then use my latest driver.

**Comment by faroukchebaiki** [comment]
which one is maintained by you

**Comment by BrightX** [comment]
> which one is maintained by you

Only in this repository.
```bash
git clone https://github.com/BrightX/rtl8192fu.git
```

**Comment by faroukchebaiki** [comment]
thanks a lot brother
